### ISSUE TITLE
When searching for a variable it does not highlight it.

### ISSUE THREAD

**Issue by jonathanqv** [jupyterlab-contrib/jupyterlab-night#15]

**Comment by martinRenou** [comment]
Thanks for opening an issue! In case you know how to fix it I'd be happy to review a PR

**Comment by jtpio** [comment]
It seems the current file is missing some `jp-search-*` variables: https://github.com/jupyterlab-contrib/jupyterlab-night/blob/main/style/variables.css

For reference the JupyterLab dark theme defines them here: https://github.com/jupyterlab/jupyterlab/blob/2607c1093539850b5b618352dc94893a8b662e48/packages/theme-dark-extension/style/variables.css#L386-L396
