### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jtpio** [jupyterlab-contrib/jupyterlab-night#20]
@martinRenou I just noticed a failed release attempt yesterday: https://github.com/jupyterlab-contrib/jupyterlab-night/actions/runs/12273597139/job/34244707295

Which looks related to the a missing credential in the release environment.

I'm taking a look now to make sure the repo is configured with everything needed.

**Comment by jtpio** [comment]
Released! https://github.com/jupyterlab-contrib/jupyterlab-night/releases/tag/v0.5.0

**Comment by martinRenou** [comment]
Thanks!
